# Generated by Django 4.1.13 on 2023-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationmodel',
            name='image',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
